version: '3'

services:
  node:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    restart: unless-stopped
    env_file: .env
    ports:
      - "${ELEVENTY_PORT:-3000}:3000"
      - "${NETLIFY_PORT:-3001}:3001"
    volumes:
      - .:/app
      - node_modules:/app/node_modules

volumes:
  node_modules:
