name: "avancarte"
version: "3.7"

services:
  node:
    build:
      context: "."
      args:
        - NODE_ENV="${NODE_ENV:-production}"
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    restart: "unless-stopped"
    stop_grace_period: "3s"
    env_file: ".env"
    tty: true
    init: true
    ports:
      - "${FORWARD_ELEVENTY_PORT:-3000}:3000"
      - "${FORWARD_NETLIFY_PORT:-3001}:3001"
    volumes:
      - ".:/app"
      - "node_modules:/app/node_modules"

volumes:
  node_modules:
