name: "avancarte"

services:
  node:
    build:
      context: "."
      args:
        - "NODE_VERSION=${NODE_VERSION:-16.14.2}"
        - "NODE_ENV=${NODE_ENV:-production}"
        - "UID=${UID:-1000}"
        - "GID=${GID:-1000}"
    command: "npm start"
    restart: "unless-stopped"
    env_file: ".env"
    tty: true
    init: true
    ports:
      - "${FORWARD_ELEVENTY_PORT:-3000}:3000"
      - "${FORWARD_NETLIFY_PORT:-3001}:3001"
    volumes:
      - ".:/app"
      - "/app/node_modules"
