[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "16.14"

[context.production.environment]
  URL = "https://avancarte.netlify.app"
  TZ = "Europe/Berlin"

[[redirects]]
  from = "*"
  to = "/404"
  status = 404
